---
# tasks file for setup-ansible-user
- name: Create new user on managed node
  user:
    name: "{{ remote_user }}"
    groups: wheel
    append: yes

- name: Add key to managed node
  authorized_key:
    user: "{{ remote_user }}"
    key: "{{ remote_user_public_key }}"
    manage_dir: yes

- name: Add sudo entries for new user
  copy:
    content: "{{ remote_user }} ALL=(ALL) NOPASSWD: ALL"
    dest: "/etc/sudoers.d/{{ remote_user }}"
